<a href="https://colab.research.google.com/github/alina-bogdanovskaya/Math_Sep2021/blob/lesson7/Linear_algebra_lesson7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
import numpy as np

In [2]:
A = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
B = np.array([[3, 3, 3], [3, 3, 3], [3, 3, 3]])
C = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])
k = 2
l = 3

In [3]:
res1 = (k * l) * A
res2 = k * (l * A)

print(res1)
print(res2)

comparison = res1 == res2
print(comparison.all())

[[12 12 12]
 [12 12 12]
 [12 12 12]]
[[12 12 12]
 [12 12 12]
 [12 12 12]]
True


In [4]:
res1 = k * (A + B)
res2 = k * A + k * B

print(res1)
print(res2)

comparison = res1 == res2
print(comparison.all())

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
True


In [5]:
res1 = (k + l) * A
res2 = k * A + l * A

print(res1)
print(res2)

comparison = res1 == res2
print(comparison.all())

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
True


In [6]:
res1 = (A * B) * C
res2 = A * (B * C)

print(res1)
print(res2)

comparison = res1 == res2
print(comparison.all())

[[24 24 24]
 [24 24 24]
 [24 24 24]]
[[24 24 24]
 [24 24 24]
 [24 24 24]]
True


In [7]:
res1 = (A + B) * C
res2 = A * C + B * C

print(res1)
print(res2)

comparison = res1 == res2
print(comparison.all())

[[20 20 20]
 [20 20 20]
 [20 20 20]]
[[20 20 20]
 [20 20 20]
 [20 20 20]]
True


In [8]:
res1 = A * (B + C)
res2 = A * B + A * C

print(res1)
print(res2)

comparison = res1 == res2
print(comparison.all())

[[14 14 14]
 [14 14 14]
 [14 14 14]]
[[14 14 14]
 [14 14 14]
 [14 14 14]]
True
